openapi: 3.0.0
info:
  title: Mobile Banking API
  description: API for the Mobile Banking application
  version: 1.0.0
  contact:
    name: Bank of Checkmarx
    email: support@bankofcheckmarx.com

servers:
  - url: http://localhost:8081
    description: Development server

paths:
  /api/v1/health:
    get:
      summary: Health check
      description: Check if the API is running
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

  /api/v1/login:
    post:
      summary: User login
      description: Authenticate user and return session token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /api/v1/accounts:
    get:
      summary: Get user accounts
      description: Retrieve all accounts for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /api/v1/transfers:
    post:
      summary: Create transfer
      description: Create a new money transfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Transfer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        created_at:
          type: string
          format: date-time

    Account:
      type: object
      properties:
        id:
          type: string
        account_number:
          type: string
        balance:
          type: number
        currency:
          type: string
        account_type:
          type: string

    Transfer:
      type: object
      properties:
        id:
          type: string
        from_account:
          type: string
        to_account:
          type: string
        amount:
          type: number
        currency:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time

    TransferRequest:
      type: object
      required:
        - from_account
        - to_account
        - amount
        - currency
      properties:
        from_account:
          type: string
        to_account:
          type: string
        amount:
          type: number
        currency:
          type: string 