apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-banking-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: mobile.bankofcheckmarx.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-banking-service
            port:
              number: 80
  tls:
  - hosts:
    - mobile.bankofcheckmarx.com
    secretName: mobile-banking-tls 