apiVersion: v1
kind: Service
metadata:
  name: mobile-app-service
  labels:
    app: mobile-app
spec:
  # Intentionally vulnerable - exposing all ports
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  - port: 443
    targetPort: 3000
    protocol: TCP
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mobile-app
  # Intentionally vulnerable - no TLS configuration
  # Intentionally vulnerable - no network policies
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mobile-app-network-policy
spec:
  podSelector:
    matchLabels:
      app: mobile-app
  # Intentionally vulnerable - allowing all ingress
  ingress:
  - {}
  # Intentionally vulnerable - allowing all egress
  egress:
  - {}
  # Intentionally vulnerable - no namespace restrictions
  policyTypes:
  - Ingress
  - Egress 